
services:
  web:
    image: nginx:alpine
    container_name: my-nginx
    ports:
      - "127.0.0.1:8080:80" # Bind to localhost for security
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
